/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.tienda.grpc.Producto;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author norma
 */
public class InventarioFrame extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
     * Creates new form InventarioFrame
     */
    public InventarioFrame() {
        initComponents();
        mejorarTabla();
        this.modelo = (DefaultTableModel) tablaInventario.getModel();
    }

    public void actualizarInventario(Map<String, Producto> inventario) {
        modelo.setRowCount(0);

        for (Producto p : inventario.values()) {
            Object[] fila = {
                p.getId(),
                p.getNombre(),
                p.getPrecio(),
                p.getCantidad()
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Stock"
            }
        ));
        jScrollPane1.setViewportView(tablaInventario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mejorarTabla() {
        // Cambiar fuente y tamaño de la tabla
        tablaInventario.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        tablaInventario.setRowHeight(25);

        // Colorear encabezado
        tablaInventario.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        tablaInventario.getTableHeader().setBackground(new java.awt.Color(60, 63, 65)); // gris oscuro
        tablaInventario.getTableHeader().setForeground(new java.awt.Color(255, 255, 255)); // blanco

        // Colorear filas alternadas
        tablaInventario.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    setBackground(new java.awt.Color(100, 149, 237)); // azul selección
                    setForeground(java.awt.Color.WHITE);
                } else {
                    setBackground(row % 2 == 0 ? new java.awt.Color(245, 245, 245) : java.awt.Color.WHITE);
                    setForeground(java.awt.Color.BLACK);
                }
                return this;
            }
        });

        // Quitar líneas de cuadrícula o hacerlas más sutiles
        tablaInventario.setShowGrid(true);
        tablaInventario.setGridColor(new java.awt.Color(220, 220, 220));
        tablaInventario.getTableHeader().setReorderingAllowed(false);
        tablaInventario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaInventario;
    // End of variables declaration//GEN-END:variables
}
