package gui;

import com.tienda.grpc.CarritoRequest;
import com.tienda.grpc.CarritoResponse;
import com.tienda.grpc.CarritoServiceGrpc;
import com.tienda.grpc.CarritoServiceGrpc.CarritoServiceBlockingStub;
import com.tienda.grpc.CatalogoResponse;
import com.tienda.grpc.NadaRequest;
import com.tienda.grpc.Producto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author norma
 */
public class CatalogoFrame extends javax.swing.JFrame {

    private CarritoServiceBlockingStub stub;
    private List<Producto> listaProductos;
    private DefaultTableModel modelo;

    /**
     * Creates new form CatalogoFrame
     */
    public CatalogoFrame(CarritoServiceGrpc.CarritoServiceBlockingStub stub) {
        this.stub = stub;
        initComponents();
        this.modelo = (DefaultTableModel) tablaCatalogo.getModel();    
        this.modelo.setRowCount(0);
        textCantidad.setText("");
        lblSubtotal.setText("Subtotal: $0.00");
        cargarCatalogo();
    }

    public void cargarCatalogo() {
        CatalogoResponse response = stub.obtenerCatalogo(NadaRequest.newBuilder().build());
        this.listaProductos = response.getProductosList();

        comboBoxCatalogo.removeAllItems();
        for (Producto p : listaProductos) {
            comboBoxCatalogo.addItem(p.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        comboBoxCatalogo = new javax.swing.JComboBox<>();
        textCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lblSubtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tablaCatalogo);

        comboBoxCatalogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textCantidad.setText("jTextField1");

        btnAgregar.setText("Agregar a carrito");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        lblSubtotal.setText("Subtotal:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnComprar)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblSubtotal)
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int index = comboBoxCatalogo.getSelectedIndex();
        if (index != -1) {
            Producto seleccionado = listaProductos.get(index);
            String cantidadStr = textCantidad.getText();

            try {
                int cantidad = Integer.parseInt(cantidadStr);

                if (cantidad <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
                    return;
                }

                modelo.addRow(new Object[]{seleccionado.getId(), seleccionado.getNombre(), cantidad});

                double suma = 0;
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    String id = modelo.getValueAt(i, 0).toString();
                    int cantidadProducto = Integer.parseInt(modelo.getValueAt(i, 2).toString());

                    for (Producto p : listaProductos) {
                        if (p.getId().equals(id)) {
                            suma += (p.getPrecio() * cantidadProducto);
                            break;
                        }
                    }
                }

                lblSubtotal.setText("Subtotal: $" + String.format("%.2f", suma));
                textCantidad.setText("");

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingresa un número válido en cantidad");
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío");
            return;
        }

        CarritoRequest.Builder requestBuilder = CarritoRequest.newBuilder();
        requestBuilder.setUsuarioId("USER-123");

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String id = modelo.getValueAt(i, 0).toString();
            String nombre = modelo.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());

            double precio = 0;
            for (Producto p : listaProductos) {
                if (p.getId().equals(id)) {
                    precio = p.getPrecio();
                }
            }

            Producto pCarrito = Producto.newBuilder()
                    .setId(id)
                    .setNombre(nombre)
                    .setCantidad(cantidad)
                    .setPrecio(precio)
                    .build();

            requestBuilder.addItems(pCarrito);
        }

        try {
            CarritoResponse response = stub.procesarCarrito(requestBuilder.build());

            if (response.getEstado().equals("EXITOSO")) {
                String factura = "Factura\n"
                        + "ID Transacción: " + response.getTransaccionId() + "\n"
                        + "Subtotal: $" + response.getTotalNeto() + "\n"
                        + "Impuestos (16%): $" + response.getImpuestos() + "\n"
                        + "TOTAL A PAGAR: $" + response.getTotalPagar();
                JOptionPane.showMessageDialog(this, factura);
                modelo.setRowCount(0);
                lblSubtotal.setText("Subtotal: $0.00");
            } else {
                JOptionPane.showMessageDialog(this, response.getEstado());
                modelo.setRowCount(0);
                lblSubtotal.setText("Subtotal: $0.00");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            modelo.setRowCount(0);
            lblSubtotal.setText("Subtotal: $0.00");
        }
    }//GEN-LAST:event_btnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> comboBoxCatalogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JTable tablaCatalogo;
    private javax.swing.JTextField textCantidad;
    // End of variables declaration//GEN-END:variables
}
